version: "3"
services:
  dev:
    container_name: betree-dev
    stdin_open: true
    tty: true
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/usr/src/betree
